# Generated by Django 6.0.2 on 2026-03-04 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeProjeto', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=255)),
                ('dataInicio', models.DateField()),
                ('dataFim', models.DateField()),
                ('prioridade', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeTarefa', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=20)),
                ('dataInicio', models.DateField()),
                ('dataFim', models.DateField()),
                ('prioridade', models.CharField(max_length=10)),
                ('etiqueta', models.CharField(max_length=30)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='app.projeto')),
            ],
        ),
    ]
