# Generated by Django 6.0.2 on 2026-03-04 14:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='dataFim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='dataInicio',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
