# Generated by Django 6.0.2 on 2026-03-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_projeto_datafim_alter_projeto_datainicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='prioridade',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('todo', 'A Fazer'), ('doing', 'Fazendo'), ('done', 'Concluído')], default='todo', max_length=10),
        ),
    ]
