# Generated by Django 6.0.2 on 2026-03-11 15:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_tarefa_prioridade_alter_tarefa_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='dataFim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='dataInicio',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
