# Generated by Django 6.0.2 on 2026-03-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_tarefa_datafim_alter_tarefa_datainicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='prioridade',
            field=models.IntegerField(default=0),
        ),
    ]
