# Generated by Django 6.0.2 on 2026-03-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_projeto_prioridade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='prioridade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
